name: Django CI/CD

on:
  push:
    branches: [ "main" ]  # Runs on pushes to main branch
  pull_request:
    branches: [ "main" ]  # Runs on PRs targeting main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # Checks out your code
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Use your Django's Python version
    
    - name: Install dependencies
      run: |
        cd practice_pro
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd ..
        
    - name: Run tests
      run: |
        cd practice_pro
        python manage.py test
        cd ..
